Multiprotocol/Hontai_nrf24l01.ino
Fixed code so that the X5C1 uses the JJRC protocol instead of the HONTAI protocol, also disabled trims for X5C1 as it causes the quad to become unstable/unflyable due to the controlls pulling the trim to either ends.
=> Fix hontai code for X5C1

docs/Compiling.md
This has the advantage not modifying the other boards and the user needs to only edit one file instead of two.
=> Move multi specific compiler flags to multi board definition

docs/Tx-Taranis.md
Some people are (also one of us Devs) are experiencing that the module sometimes stops. We haven't found a real reason for that and are still investigating. No this scenario also in the docs.
=> add no_multi_telemetry as indicator of crashed

Multiprotocol/DSM_cyrf6936.ino
Spektrum own remotes transmit normal values during bind and actually use this (e.g. Nano CP X) to select the transmitter mode (e.g. computer vs non-computer radio, so always end normal output
=> DSM: Remove special bind stick positions

docs/BOM_DIY_STM32 & Schematic.md
Added Digi-Key shared carts for latest build BOM. 
Need to confirm if SV202,SV203, and SV204 each need a strip of 40 header pins for a total of 120 pins as currently since each S1011EC-40-ND part has 40  pins?
=> Update BOM_DIY_STM32 & Schematic.md

Multiprotocol/Validate.h, Multiprotocol/_Config.h
Rather than silently disabling CHECK_FOR_BOOTLOADER  lets throw an error prompting the user to make the correct selection.
This should prevent accidentally compiling firmware which doesn't have bootloader support.
=> Warn if CHECK_FOR_BOOTLOADER is enabled but a NO_BOOT board is selected

Multiprotocol/Validate.h
Add `#undef` for new  esky150 and H8_3D protocols if `NRF24L01_INSTALLED` is not defined.
=> Update Validate.h for two new NRF24L01 protocols

Multiprotocol/Multiprotocol.ino, Multiprotocol/Validate.h, Multiprotocol/_Config.h, docs/Frequency_Tuning.md
Adds an option so that once known-good tuning values have been determined, they can be stored in the configuration file and be automatically applied to all models which use the given protocol.
Can also be used to force different tuning values for different multiprotocol modules, removing the need to alter the tuning option on the transmitter when swapping between modules.  (Assuming that the modules also share a common hardware ID.)
I tested this in my 9XR Pro with Atmega328 and STM32 modules, bound to an FrSky X8R, with the module in serial mode.  My modules share the same hardware ID.
* With `FORCE_FRSKYX_TUNING` undefined I was able to use the radio to control the tuning frequency
* With different values set for `FORCE_FRSKYX_TUNING` for the Atmega and STM32 modules I was able to swap …
=> Add options to globally set frequency tuning values for FrSky and SFHSS protocols

docs/Compiling_STM32.md
The previous documentation included steps to get a rules file from the libmaple github repository. This was unnecessary as the given file is already included in this project in a tools directory. Changed the documentation to use that file directly. Also improve explanation of what password sudo is requesting.
=> Simplify STM32 Linux compilation steps.

Multiprotocol/Multiprotocol.ino
Also fix that stm32 id is always either 0 or stm32 id
=> Fix module id returned to be 0 when saved to eeprom

BootLoaders/package_multi_4in1_board_index.json
* Adds short delay when uploading via USB to give board time to reset before IDE looks for the serial port
* Fixes maximum upload size to take into account EEPROM emulation and bootloader
* Fixes stm32flash scripts so that EEPROM data is not erased when uploading via serial
=> Release stm32 board v1.0.9

Multiprotocol/_MyConfig.h.example
This is a correction of a small error in the _MyConfig.h.example file listing #define Module_2 twice instead of #define Module_3
@pascallanger Also seeing if this can be merged into master from my repo?
Thanks - Rich
=> Correction in example file of #define Module_3

Protocols_Details.md
This PR adds a Table of Contents chart for quick reference of all current available protocols with quick links to each protocols descriptive breakdown. 
Also makes navigating this lengthy file much easier.
@pascallanger  While researching for this project, there is no description breakdown for the CFlie protocol. I'm not sure how to describe it or I would have included it in this PR. 
Also I have included Traxxas in the TOC, although I know it is a future project and currently not available, but it is listed as Protocol 43 in the Multi.txt file
Thanks - Rich
=> Add Table of Contents

Multiprotocol/MJXQ_nrf24l01.ino
- Fix E010/CC2500 Protocol on AVR (wrong xn297 crc)
- Use fast frequency hopping mode
=> Fix E010/CC2500 Protocol on AVR

docs/Compiling_STM32.md
@pascallanger  Please review this for any unknown errors. My knowledge  is limited as I have not used the new Flash-Multi to upload a pre-compiled binary.
This PR breaks the instructions into the two options that are now available  to update the STM Module.
It seemed to all run together causing future confusion on updating?
Hopefully this will better describe and separate the two processes available?
Thanks - Rich
=> Add option instructions to update STM module

Multiprotocol/Multiprotocol.ino, docs/Troubleshooting.md
* Wait 30s for serial debug at startup instead of waiting forever
* Double-blink LED while waiting for serial debug
* Delay of 50ms to allow FTDI debugger to connect at startup
=> Serial Debug Enhancements

Multiprotocol/Multiprotocol.ino
Adds variables which post-compilation scripts can use to detect build options and set the signature in the .bin file.
=> Add flag variables for binary file signature

Multiprotocol/FrSkyX_Rx_cc2500.ino, Multiprotocol/FrSkyX_cc2500.ino, Multiprotocol/Multiprotocol.h, Multiprotocol/Multiprotocol.ino, Multiprotocol/Telemetry.ino, Multiprotocol/Validate.h, Multiprotocol/_Config.h
Add FrSky D16 receiver protocol to be used as a wireless training "cable" by OpenTX 2.3+
Protocol#: 55
sub proto 0: FCC
sub proto 1: EU(LBT)
option: frequency fine tune
low power mode: disable lna
=> Protocol FrSky D16 receiver

Protocols_Details.md
TOC listed the following sub protocols in wrong column. Both should be listed under "Sub_Proto 0"
FlyZone  FZ410
Traxxas   RX6519
Also after review,
Under the FY326 Protocol descriptions, The FY319 Sub Protocol Option "1" was not listed.
Not sure if the FY319 has the same channel order but seems to be untested as well?
Please add or delete as needed - Rich
=> Repair Protocol Table of Contents listings

.travis.yml
Ensures that one or more individual protocol tests failing will cause the entire test to fail, properly bubbling up the individual failure.
=> Return correct accumulated exit codes for individual protocol tests

.travis.yml, buildroot/bin/opt_replace
Various improvements to the Travis CI script:
* Add channel order builds to releases - now building AETR, TAER, and RETA
* Add PPM builds for each channel order with no inversion and PPM banks set to 5
* Log config diff for each build (diff output folded to keep the log readable)
* Colorify the "Building" lines to make parsing the log easier
* Export .bin files instead of .hex files for the AVR modules
* Add Multi.txt to the release files
=> Update Travis Configuration

Multiprotocol/Multiprotocol.ino, Multiprotocol/Pins.h, Multiprotocol/Validate.h, Multiprotocol/_Config.h
As far we have few unused pins on stm32 it's possible to wire inputs to this pins. 
I'd install multiprotocol moule to my old Spektrum DX6i and it works like a charm, but since I started play with multirotors I expirenced some lack of channels for all this arm/beep/flight mode... 
This PR solved my problem and can help someone else.
Of course it's not easy enough to wire thin wires directly to stm32 pins, but not impossible. BTW we have 1 pin that can be used as-is without soldering - DEBUG_PIN. But I prefer PC13, PC14, PC15 and also we can use PB0 as analog input.
If you know another unused pins that an be used without soldering - it will be great!
Since my code do not break any existing logic - it's safe to merge. If you need some more explanations or fixes - let me know!
=> Direct inputs

Multiprotocol/Telemetry.ino
erSkyTX on my 9XR-Pro would not display the MULTI-Module firmware version number when it had the channel order appended.
=> Fix module status on erSkyTX

Multiprotocol/FrSkyDVX_common.ino, Multiprotocol/FrSkyX_cc2500.ino, Multiprotocol/FrSky_Rx_cc2500.ino
- Bind an FRSKY_X Transmitter with RX-Number 15 (Should be changed to 63, but I'm on OTX2.2.x at the moment and there is 15 the highest RX-Number) to your secondary TX using Multimodule in FRSKY-RX mode.
- Use a secondary TX to create (or copy) a model using Multimodule in FRSKY-TX mode and use the RX-Number of the model in the original TX
Now you can use both transmitters without rebinding the RX
It's useful, if you have a full size TX like Taranis or Horus and a second lightweight TX like XLite.
=> Initial Version of CloneMode

Multiprotocol/SX1276_SPI.ino
Some registers should be adjusted for optimal sensitivity at 500khz bandwidth
=> Implements datasheet errata recommendation

Multiprotocol/SX1276_SPI.ino
Works by testing for 0x12 match in version reg 0x42.
Not 100% needed, but nice for debugging.
=> Adds SX1276_DetectChip() function

.travis.yml
The Arduino IDE used in Travis creates builds that are on average 2KB larger than the Arduino IDE on Windows, or the Arduino CLI on any platform.  Switching to the CLI will give us back 2KB of flash and make the build consistent across platforms.   Using the Arduino CLI also makes the builds faster across the board, reducing the time it takes to test from ~10mins to ~6mins.
The underlying toolchain (board, compiler, and core) is unchanged.
=> Switch to Arduino CLI instead of IDE for Travis CI builds

Multiprotocol/Multiprotocol.h, Multiprotocol/Multiprotocol.ino
Updates the flash size check to set the expected size according to the MCU.  Allows the user to compile and use firmware on a C8 MCU using the new board package, without completely disabling the flash size check.
=> C8 MCU flash size check

.travis.yml
Updates Travis to use the latest board package and do tests for the F103C8 board (testing non-debug only as debug builds don't fit).
=> Add tests for STM32F103C8 board

Multiprotocol/OMP_cc2500.ino, Multiprotocol/Validate.h
Not sure if this will be right, but thought I'd have a go :)
* Disable DSM_FWD_PGM if telemetry is disabled
* Only define OMP_Send_Telemetry if OMP telemetry is enabled
=> Fix compiler errors when telemetry is disabled

Multiprotocol/Multiprotocol.ino
Calls the `EEPROM.init` function at startup to check/initialize the EEPROM.  If there is no valid EEPROM page the EEPROM is formatted by calling `EEPROM.format`.
Solves the problem discovered in #473 where bad data in the EEPROM section of flash causes EEPROM reads and writes to fail.
Normal first startup with no EEPROM data:
```
Multiprotocol version: 1.3.1.78
EEPROM initialized: 0
Protocol selection switch reads as 0
Generated ID from STM32 UUID
Module Id: 73739e23
Init complete
```
Normal subsequent startup with valid EEPROM data:
```
Multiprotocol version: 1.3.1.77
EEPROM initialized: 0
Protocol selection switch reads as 0
Read ID from EEPROM
Module Id: 73739e23
Init complete
```
Startup with invalid EEPROM data (status 171 = no valid EEPROM page):
```
Multiprotocol version: 1.3.1.77 …
```
=> Add STM32 EEPROM initialization at startup

.travis.yml
The latest version of arduino-cli doesn't seem to like our board packages.  Force the builds to use arduino-cli 0.13.0 until it is resolved.
=> Pin arduino-cli version to 0.13.0

.github/workflows/main.yml, buildroot/bin/buildFunctions, buildroot/bin/build_release_avr_noboot, buildroot/bin/build_release_avr_optiboot, buildroot/bin/build_release_orx, buildroot/bin/build_release_stm32f1_native_debug, buildroot/bin/build_release_stm32f1_no_debug, buildroot/bin/build_release_stm32f1_serial_debug, buildroot/bin/build_release_stm32f1_t18int
* Run tests if the build scripts are modified (as well as if the FW source is modified)
* Fix AVR release builds so that correct protocols are included/excluded
* Fix AVR no-bootloader CC2500 build so that failures bubble up
* Exclude OMP from the AVR CC2500 build so that it fits (excluded protocols are now Hitec, Redpine, OMP, Skyartec, and Scanner)
=> Various fixes for CI workflow

Multiprotocol/AFHDS2A_a7105.ino, Multiprotocol/HOTT_cc2500.ino, Multiprotocol/Multiprotocol.h
Fixes the problem where AFHDS 2A RX binds are not stored if the RX number is higher than 17, and seemingly (although untested) the same problem for Hott.
* AFHDS 2A RX numbers >17 result in EEPROM addresses >255, which overflowed the uint8 address variable
* All Hott RX EEPROM addresses are >255, also overflowing the uint8 address variable
=> Fix EEPROM address variable types for AFHDS 2A and Hott

Multiprotocol/CABELL_nrf224l01.ino
Matches the spec: https://github.com/soligen2010/RC_RX_CABELL_V3_FHSS/blob/41691db0934c5d747a6b612414211cb5023b27ca/RX.h#L92
=> Set reserved field in CABELL packet to current channel

buildroot/bin/buildFunctions, buildroot/bin/build_release_stm32f1_64k
Adds the three channel order builds for a CC2500-only module with the STM32F103C8 MCU, like we're seeing in some TX12 radios.  With all CC2500 protocols except IKEA the build is at 53172 bytes (96%).
I still need to update the downloads page to show / filter them properly.
=> Add release builds for 64KB CC2500-only module

buildroot/bin/build_release_stm32f1_no_debug
Added a way to disable protocols for the DIY 5-in-1 release builds and disable MOULD KG by default.  In the future we will almost certainly have to do this for other builds.
Suggestions for other protocols we might want to disable by default:
* Cabell
* LOLI
* Redpine
AFAIK these are all DIY protocols so are probably used by a small number of users, and anyone who does use them should be capable of compiling firmware themselves.
=> Disable some protocols for the DIY 5-in-1 release builds

Multiprotocol/HOTT_cc2500.ino, Multiprotocol/Telemetry.ino
This allows processing of HoTT device warnings by the OpenTX HoTT telemetry implemenation, please see the accompanying OpenTX PR https://github.com/opentx/opentx/pull/8767
Content:
This adds one additional byte to the data packet transferred to OpenTX. Please see attached file for details of data the byte content.
Implementation:
HOTT_cc2500.ino: incoming byte 10 holds the warning number issued by HoTT devices. This byte is saved and transferred as packet_in[14] to Opentx.
Telemetry.ino:
The number of bytes to be transferred to OpenTX is incremented from 13 to 14  
Attachments:
[HoTT warnings.txt](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/7467657/HoTT.warnings.txt)
=> Graupner HoTT protocol / added packet_in[14] to transfer HoTT device warnings to OpenTx

Lua_scripts/DSM FwdPrg.lua
Fixed a few "Unknown_" strings when testing FP on RM TX16S with EdgeTx and a couple of Spektrum Rxs. AR636B from a Blade230SV2 and an AR637TA in an E-flite Viper 90mm. Both unlocked BNF Rxs.  Using iX20 as a reference.
Also found a conflict between Rx name string "AR636B" and Text string "On", both using index 0x0001. Resolved by having Rx names in a separate string array.
=> Text updates in Spektrum Fwd Prog LUA script

Protocols_Details.md
I successfully tested the V911S/E119 protocol with my XK A800. With the changes contained in b740f4cd24d8a63637c5dddeccd074327caddfcd the 6G3D switching is working as well.
=> mention XK A800 in V911S/E119 details

Lua_scripts/MultiConfig.lua
The MultiConfg Lua currently does not set the subProtocol, so in cases were the subprotocol is NOT 0 (i.e. Hitec Minima - protocol 39, sub-protocol 2) - the script correctly sets the to config mode (protocol 86) but does not set the subprotocol to 0, thus config mode is not successfully entered, resulting in a "No Config telemetry" error. As was documented here => https://github.com/EdgeTX/edgetx/issues/1722#issuecomment-1077708870
This now captures the initial subProtocol state, and restores it on exit. 
Tested on TX16S internal MPM using OpenTX 2.3.15 nightly and EdgeTX 2.7 nightly.
=> MultiConfig lua should also set and reset subProtocol

Lua_scripts/Graupner HoTT Model Locator.lua
Using the Graupner HoTT telemetry sensor "Rssi" instead of the OpenTX sensor "RSSI".
Reasoning: The OpenTX sensor "RSSI" is populated by the individual OpenTX telemetry protocol implementations and returns a value from 0..100 (percent) originating from the early FrSky implementation. It turns out that FrSky did not really provide a genuine signal strength indicator in units of dbm but a link quality indicator in 0..100%. With Graupner HoTT the link quality indicator is not a good basis for the model locator as it is very non-linear and doesn't change much with distance. Using the Graupner HoTT telemetry sensor "Rssi" which is a true signal strength indicator serves the purpose of locating a model much better as it varies much more with distance.
=> Graupner HoTT adapted version of the Model Locator script

.github/workflows/main.yml, buildroot/bin/buildFunctions
This PR switches the CI process to use the 'devel' version of the MULTI Arduino board package.  The devel board uses a newer GCC compiler (gcc-8.3.1) which generates smaller firmware builds.  Once merged, all automated test and release builds will be done with the new board and compiler.
Switching the CI job to the devel board will enable us to get more testing with firmware built with the new compiler, ultimately enabling us to switch all builds over.
=> Use devel boards in CI workflow

Lua_scripts/DSM FwdPrg.lua
Reversing 'Off' and 'On' text values in lines 555 and 556.  They are used in the SAFE and AS3X menu items in the DSM Forward Programming section, and they are functioning backwards. This will correct the issue. This is the fix for Issue #728
=> Update DSM FwdPrg.lua

docs/Compiling_STM32.md
This patch adds documentation, explaining how to flash firmware to DFU
capable multimodules.
A dfu-util command was taken and adapted from:
https://github.com/benlye/flash-multi/blob/master/doc/Troubleshooting.md
Using dfu-util is straight forward, easy and very safe.
=> Added documentation for using dfu-util for flashing STM32 targets.

.github/workflows/main.yml
Workaround to the broken binary file signature problem #862 by using the previous version of Arduino CLI.
=> Fix builds by using older Arduino CLI

Lua_scripts/MultiConfig.lua
The MultiConfig lua script seemed to have problems with 0x00 values for either ID. It also didn't appear to have any protection against attempting to enter negative numbers or those larger than 0xFF.
I tested the changes with a Radiomaster Boxer running EdgeTX 2.9.1 and 4-in-1 version 1.3.3.33 and it seems to fix the issue.
=> Allow zero and limit range of enterd values

.github/workflows/main.yml, buildroot/bin/build_release_stm32f1_64k, buildroot/bin/build_release_stm32f1_no_debug, buildroot/bin/opt_remove
* Adds EU/LBT binaries for three types of module (STM32F103CB 4in1, STM32F103CB CC2500, and STM32F103C8 CC2500)
* Gives each matrix build in the CI job a more intuitive name
* Cleanup some old commented-out lines
=> Add EU/LBT binaries to the build artifacts

Multiprotocol/DSM_cyrf6936.ino
Fixes #916
Tested with multiple brands (Spektrum, OrangeRX, Lemon-Rx, Admiral).  Even some old DSM 2 receivers.
Lemon-RX needed a short Bind Send period (180 count, about 1.8s instead of 3s)
All brands works with "Auto" now.   Just in case one needs a LONG bind sending period, when not using "Auto" works the same as before.
=> Fix for DSM-Auto Bind on Lemon-RX Gen2

buildroot/bin/build_release_stm32f1_cc2500_64k
Need to disable a protocol to get the release builds to fit on the 64kb CC2500 module. SCANNER is probably the least used.
=> Disable SCANNER in CC2500 64kb builds

.github/workflows/main.yml
Gets rid of the numerous  
> "The following actions uses Node.js version which is deprecated and will be forced to run on node20" 
warnings which are present in the action summary. And while it is still quite some time away, Github will be [ceasing support for NodeJS 16 actions by Spring 2024](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).
=> chore(ci): bump setup-arduino-ci version to remove nodejs warning

Protocols_Details.md, README.md
The protocols no longer fit on the STM32, it might be useful to update the README and Protocol Details to reflect this. It might also be helpful to mention the surface and air groups in the available compiled firmware on the Multi-Module website.
=> Update readme and protocol detals with surface/air info

Multiprotocol/FX_nrf24l01.ino, Multiprotocol/Multi.txt, Multiprotocol/Multi_Protos.ino, Multiprotocol/Multiprotocol.h, Multiprotocol/_Config.h
This is for https://m.banggood.com/QF012-SBD-Dauntless-2_4GHz-4CH-350mm-Wingspan-6-Axis-Gyro-One-Key-Aerobatic-Brushless-EPP-Warbird-RC-Airplane-RTF-p-2028163.html
Add after 
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Protocols_Details.md#sub_protocol-q560---3
Sub_protocol QF012 - 4
Model: QF012 SBD Dauntless
CH1	CH2	CH3	CH4	CH5	CH6	CH7
A	E	T	R	FLIP	GYRO	Invert
Thanks.
=> Add FX_QF012 subprotocol

Multiprotocol/RadioLink_cc2500.ino
Tested with X6FGv1.1, X6FP, X6DC(G)v1.1
I also tested with multiple X6F receivers and some gave RSSI Telem and some gave nothing. 2 of them had the same PCB as the X6FP and neither gave telemetry. I had a third with the same PCB with the X6FP which did give RSSI and of my two with an older PCB one gives RSSI telem and the other does not.
Of the receivers I tried only one set packet_in[6] to match the TX packet[1] and it was the oldest receiver of the ones I own.
=> Enable Telemetry on DumbRC receivers
