- Multiprotocol/Multiprotocol.h
- Multiprotocol/Multiprotocol.ino
- Multiprotocol/Telemetry.ino
- Multiprotocol/_Config.h
I made these changes so I could use my existing diy nrf24_multipro module and was able to get it working.
The changes should be tested with a DIY Multiprotocol TX Module to make sure I didn't break anything.
> made pins configurable and added support for nano

- Multiprotocol/AFHDS2A_a7105.ino
- Multiprotocol/Multiprotocol.h
- Multiprotocol/Multiprotocol.ino
- Multiprotocol/Telemetry.ino
- Multiprotocol/_Config.h
New telemetry protocl for OpenTX (and possible ersky9x)
- Telemetry protocol selected by module instead of TX
- Status and version of the multiprotocol module sent to TX
> Multi telemetry

- docs/Compiling.md
😨 I forgot 1 commit (purely cosmetic).
Sorry. 😢 
I'm done.
😄
> Align pictures in Compiling.md

- docs/Bind_Timing.md
- docs/Compiling.md
- docs/Documentation_To_Do_List.md
- docs/Protocol_Details_old.md
- docs/Tx-FlyskyTH9X.md
- docs/Tx-Taranis.md
- docs/Tx-erSky9X.md
I missed the transmitter's sections. It is now corrected.
> More fixes in the documentation.

- docs/Module_Build_yourself_PCB.md
Fixed broken link. Bad idea to use space and ampersand... ;)
> Fixed broken link

- docs/Compiling.md
- docs/Flash_from_Tx.md
- Update the doc for compiling for Atmega to include using the Arduino IDE board defintion
- Add instructions for flashing the module from the Tx
> Documentation updates

- Multiprotocol/Telemetry.ino
Sorry for breaking non MULTI_TELEMETRY S.port polling
> Fix multi status

- .travis.yml
- buildroot/bin/opt_add
- buildroot/bin/opt_disable
- buildroot/bin/opt_enable
- buildroot/bin/opt_set
Adding configuration and scripts for Travis CI build tests.
> Configure Travis CI

- .travis.yml
- buildroot/bin/opt_disable
- buildroot/bin/opt_enable
Changes to the Travis configuration and helper scripts so that the individual protocol builds actually work, and new protocols are automatically tested as well.
FYI, Travis will throw an error when testing this PR until #198 is merged.
> Fix individual protocol builds

- Protocols_Details.md
Table of Contents update for the CC2500 emulating the XN297L with 250 kbps.
Please review and make changes if needed.
Thanks - Rich
> Update Protocols_Details.md TOC Protocols using CC2500 to emulate XN297L @250 kbps

- Multiprotocol/Multiprotocol.h
- Multiprotocol/Validate.h
Not sure if this is how you wanted to do this, but it's simple and it works :-)
> Enable DEBUG_SERIAL based on Arduino IDE Debug Option menu

- docs/Arduino_IDE_Boards.md
- docs/Compiling_STM32.md
Take a look and see what you think.  I moved the driver stuff to the board installation page to make the compiling page even shorter.
We'll still need to add something about how to use the new Debug Option for USB/serial debugging.
> Doc updates for new board package

- .travis.yml
* Use latest STM32 board options
* Use latest Arduino IDE
* Fix build functions to return an error if the build fails
* Modify the files that get exported to releases
> Update Travis CI script

- Multiprotocol/Scanner_cc2500.ino
Wait until telemetry packet is sent before continuing scanning ...
> Fix scanner telemetry

- Multiprotocol/FrSkyX_Rx_cc2500.ino
- Multiprotocol/Multiprotocol.h
Auto-tune FrskyX D16 RX frequency during bind.
The value is used during data phase if freq. fine tune is set to 0.
> Protocol FrskyX D16 RX frequency auto-tune

- .travis.yml
- buildroot/bin/opt_replace
* Export TAER and RETA binaries in releases as well as AETR
* Add channel order to all file names
* Export .bin files instead of .hex for AVR builds
* Add Multi.txt to the release files
* Add `git diff` commands prior to each build to make it easier to verify the actual options being built
* Add colours to the some of the output lines to make parsing the logs easier
> Travis updates

- Multiprotocol/Binary_Signature.ino
- Multiprotocol/Multiprotocol.ino
This won't break the existing signature behaviour so should be safe to merge at any time.
> Move signature conditionals to separate file, add channel order

- Multiprotocol/AFHDS2A_Rx_a7105.ino
Fix AFHDS2A receiver channel and rssi scaling
> Fix AFHDS2A receiver channel and rssi scaling

- Multiprotocol/AFHDS2A_Rx_a7105.ino
> Fix AFHDS2A channel scaling for +125%

- Multiprotocol/Bayang_Rx_nrf24l01.ino
- Multiprotocol/Multi_Names.ino
- Multiprotocol/Multiprotocol.h
- Multiprotocol/Multiprotocol.ino
- Multiprotocol/Telemetry.ino
- Multiprotocol/Validate.h
- Multiprotocol/_Config.h
- Protocols_Details.md
Add Bayang RX protocol (#59), to be used as master trainer input by OpenTX 2.3+
> Protocol Bayang rx

- Multiprotocol/Redpine_cc2500.ino
Just tested out on stm32 multi using both fast and slow on a taranis 9xd+
Also multisync appears to be working well.  Although for the fast protocol the minimum is 6ms for the sync, where the protocol is sending every 2ms.
> Redpine updates to make multi-redpine work released betaflight and deviation builds

- Multiprotocol/JJRC345_nrf24l01.ino
A largely symbolic contribution to record participation in protocol development.
See: https://github.com/DeviationTX/deviation/pull/853
> JJRC345: Reduce stick sensitivity for flips

- .travis.yml
Also fixes CC2500 release builds for Atmega (they had become to big so I have excluded a few protocols from the CC2500 build).
> Add Travis tests and release builds for T18 5in1

- .travis.yml
Creates the TOOLS/SCRIPTS folder structure for the LUA scripts in the release .zip file
> Create folders in LUA script zip file

- .travis.yml
SCRIPTS\TOOLS, not TOOLS\SCRIPTS!
> Fix folder structure inside LUA script zip file

- .travis.yml
* Disable PPM in the serial (OpenTX/erSkyTX) release builds
* Disable serial in the PPM release builds
> Disable PPM/serial in STM32 builds as needed

- Multiprotocol/Binary_Signature.ino
Differentiates between the STM32F1 boards.
> Add module sub-type to signature

- BootLoaders/package_multi_4in1_board_index.json
Update the boards index file for anyone who is getting it from this repo.
> Add latest boards

- buildroot/bin/build_release_avr_noboot
- buildroot/bin/build_release_avr_optiboot
- buildroot/bin/build_release_orx
- buildroot/bin/build_release_stm32f1_native_debug
- buildroot/bin/build_release_stm32f1_no_debug
- buildroot/bin/build_release_stm32f1_serial_debug
- buildroot/bin/build_release_stm32f1_t18int
Better for radios with 128x64 LCDs.
> Prefix release binaries with mm instead of multi

- Lua_scripts/DSM FwdPrg.lua
A few more Spektrum Fwd Programming text updates.
Using iX20 and AR8360T ref.
> A few more Spektrum Fwd Programming text updates

- Multiprotocol/HOTT_cc2500.ino
This fix allows setting failsafe values without having to rebind and sets failsafe values correctly for all possible 16 channels.
Notes for OpenTX/EdgeTX:
This fix doesn't exhibit servo jitter if failsafe mode was left on Custom, however it is still recommended to set failsafe mode back to Receiver after setting failsafe values.
It is still necessary to wait at least 8 seconds switching back from failsafe mode Custom to failsafe mode Receiver as OpenTX/EdgeTX will trigger the data transfer in Custom mode only every 7 seconds.
Bench tested with HoTT receivers GR-16, GR-24pro, GR-32
Flight tested with HoTT receiver GR-24
> Fixes a problem where setting failsafe values was only possible once after bind and only set values for the first 12 channels.

- Multiprotocol/FX_nrf24l01.ino
- Multiprotocol/Multi.txt
- Multiprotocol/Multi_Protos.ino
- Multiprotocol/Multiprotocol.h
- Multiprotocol/_Config.h
Implement the FX9630 for J20 jet plane by Flybear.
> FX9630 protocol support, resolves #801

- buildroot/bin/buildFunctions
- buildroot/bin/build_release_extras
- buildroot/bin/build_release_orx
Fixes the process which creates the Tools zip file so that the DSM lib subfolder is included. Addresses #897.
> Fix LUA script zipping
